-- CURRENT_DATE / CURDATE
SELECT CURRENT_DATE();
SELECT CURDATE();

-- CURRENT_TIME / CURTIME
SELECT CURRENT_TIME();
SELECT CURTIME();

-- NOW() / CURRENT_TIMESTQAMP
SELECT NOW();
SELECT CURRENT_TIMESTAMP();

-- DATE()
SELECT DATE('2026-02-12');

-- TIME()
SELECT TIME('2025-09-23 15:45:00');

-- YEAR(),MONTH(),DAY()
SELECT YEAR(NOW());
SELECT MONTH(NOW());
SELECT DAY(NOW());

-- DAYNAME(), MONTHANME()
SELECT DAYNAME('2026-09-19');
--        OR
SELECT DAYNAME(NOW());
SELECT MONTHNAME('2026-09-19');
--         OR
SELECT MONTHNAME(NOW());

-- DATE_ADD() / ADDDATE()
-- UNITS: SECOND,MINUTE,HOUR,DAY,WEEK,MOTH,QUARTER,YEAR
SELECT DATE_ADD(NOW(), INTERVAL 20 DAY);
SELECT ADDDATE(NOW(), INTERVAL 2 MONTH);

-- DATE_SUB / SUBDATE()
SELECT DATE_SUB(NOW(), INTERVAL 5 DAY);
SELECT SUBDATE(NOW(), INTERVAL 3 MONTH);

-- DATEDIFF()
SELECT DATEDIFF(NOW(), '2026-09-12');

-- TIMEDIFF()
SELECT TIMEDIFF('10:30:00','09:15:00');

-- STR_TO_DATE()
SELECT STR_TO_DATE('2026-03-30', '%Y-%m-%d');

-- DATEFORMAT
SELECT DATE_FORMAT('2025-09-23','%W %M %Y'); -- TUESDAY SEPTEMBER 2025
SELECT DATE_FORMAT(NOW(), '%d-%m-%Y %H:%i:%S'); 
